### ISSUE TITLE
Issu getting starting 

### ISSUE THREAD

**Issue by Jojo211** [grafana/influxdb-flux-datasource#10]
Hi everyone ! 

I need to install this for fix this error when I try to use my own plugin with grafana : 

> Unable to dynamically transpile ES module A loader plugin needs to be configured via `SystemJS.config({ transpiler: 'transpiler-module' })`. Instantiating http://localhost:8080/public/plugins/grafana-checkbox-panel/module.js Loading plugins/grafana-checkbox-panel/module

but I don't really get where I'm suppose to run `influxd -config`  I tried on my command line, located on the folder. But it doesn't work... 

Could anyone help me, plz ! 

Best regards

**Comment by davkal** [comment]
You dont need to install this plugin due to issues with your own plugin. This datasource plugin is a datasource plugin that you need if you have a Flux (by Influxdata) datasource.

The loading issue you have may be due to your source code being written in ES2017 or something similarly new. The grafana plugin loader expects classic JS (ES3). You need to transpile your sources to a /dist folder. For more assistance with those kinds of problems I recommend posting in https://community.grafana.com
